#!/bin/sh

echo "Installing to: ${PWD}"
sleep 3

# Download
curl -L https://github.com/assaultcube/AC/releases/download/v1.2.0.2/AssaultCube_v1.2.0.2.tar.bz2 -o AC.tar.bz2

# Unpack
tar -xvjf AC.tar.bz2
rm AC.tar.bz2

# If directory is empty, put game data in the current folder
# Otherwise put data in a new directory
count=0
for f in *
do
	count=$(( $count + 1 ))
done

if [ $count -eq 1 ]
then
	mv AssaultCube_v1.2.0.2/* .
	rmdir AssaultCube_v1.2.0.2
	acinstalldir=${PWD}
else
	mv AssaultCube_v1.2.0.2 AssaultCube
	acinstalldir=${PWD}/AssaultCube
fi

# Allow execution
cd $acinstalldir
chmod +x bin_unix/linux_64_client
chmod +x assaultcube.sh

# Remove useless dirs
rmdir demos
rm -rf docs # Docs are available online
rmdir screenshots

echo ""
echo "Adding AssaultCube to your applications menu..."
echo "If you don't want to do this, press Ctrl + C."
sleep 3

# Create a desktop entry
appdir=~/.local/share/applications/assaultcube.desktop
echo "[Desktop Entry]" > $appdir
echo "Version=1.0" >> $appdir
echo "Type=Application" >> $appdir
echo "Name=AssaultCube" >> $appdir
echo "Comment=Realistic first-person-shooter (${PWD})" >> $appdir
echo "Exec=${acinstalldir}/assaultcube.sh" >> $appdir
echo "Icon=${acinstalldir}/docs/images/icon.png" >> $appdir
echo "Path=${acinstalldir}" >> $appdir
echo "Categories=Game;" >> $appdir
chmod +x $appdir

echo ""
echo "Installed successfully!"