#!/bin/sh

echo "Downloading to: ${PWD}/AssaultCube"
echo "If you want to use a different folder, press Ctrl + C and change to that folder using cd (folder)."
sleep 5

# Download
curl -L https://github.com/assaultcube/AC/releases/download/v1.2.0.2/AssaultCube_v1.2.0.2.tar.bz2 -o AC.tar.bz2

# Unpack
tar -xvjf AC.tar.bz2
rm AC.tar.bz2
mv AssaultCube_v1.2.0.2 AssaultCube

# Allow execution
acinstalldir=${PWD}/AssaultCube
cd $acinstalldir
chmod +x bin_unix/linux_64_client
chmod +x assaultcube.sh

echo ""
echo ""
echo "Adding AssaultCube to your applications menu..."
echo "If you don't want to do this, press Ctrl + C."
sleep 5

# Create a desktop entry
appdir=~/.local/share/applications/assaultcube.desktop
echo "[Desktop Entry]" > $appdir
echo "Version=1.0" >> $appdir
echo "Type=Application" >> $appdir
echo "Name=AssaultCube" >> $appdir
echo "Comment=Realistic first-person-shooter (${PWD})" >> $appdir
echo "Exec=${acinstalldir}/assaultcube.sh" >> $appdir
echo "Icon=${acinstalldir}/docs/images/icon.png" >> $appdir
echo "Path=${acinstalldir}" >> $appdir
echo "Categories=Game;" >> $appdir
chmod +x $appdir

echo ""
echo ""
echo "Installed successfully!"